import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables')
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
})

// Database Types (will be auto-generated by Supabase CLI in production)
export type Profile = {
  id: string
  full_name: string | null
  avatar_url: string | null
  google_calendar_connected: boolean
  google_refresh_token: string | null
  google_access_token: string | null
  google_token_expiry: string | null
  trial_ends_at: string | null
  subscription_status: 'trial' | 'active' | 'cancelled' | 'expired'
  stripe_customer_id: string | null
  stripe_subscription_id: string | null
  created_at: string
  updated_at: string
}

export type Event = {
  id: string
  user_id: string
  title: string
  description: string | null
  start_time: string
  end_time: string
  all_day: boolean
  category: 'meeting' | 'deep_work' | 'admin' | 'personal' | 'break' | 'other'
  google_event_id: string | null
  google_calendar_id: string | null
  energy_level: number | null
  importance: number
  color: string | null
  location: string | null
  attendees: any[]
  created_at: string
  updated_at: string
}

export type JournalEntry = {
  id: string
  user_id: string
  event_id: string | null
  content: string
  mood: 'great' | 'good' | 'neutral' | 'bad' | 'terrible' | null
  energy_rating: number | null
  tags: string[]
  is_prompt_response: boolean
  created_at: string
  updated_at: string
}

export type SmartConflict = {
  id: string
  user_id: string
  event_id: string
  conflict_type: 'direct_overlap' | 'overload' | 'goal_impact' | 'recovery_needed'
  severity: 'low' | 'medium' | 'high'
  description: string | null
  suggestion: string | null
  resolved: boolean
  created_at: string
}
